version: "3"

services:
  nginx-proxy:
    image: budry/jwilder-nginx-proxy-arm
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    networks:
      - webnet

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:stable
    container_name: letsencrypt
    restart: always
    volumes:
      - certs:/etc/nginx/certs:rw
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    networks:
      - webnet

  space-shield:
    image: json0021/space-shield-app:latest
    container_name: space-shield-app
    restart: always
    env_file:
      - /home/.env
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=lpscad.bsenergy.co,www.lpscad.bsenergy.co
      - LETSENCRYPT_HOST=lpscad.bsenergy.co,www.lpscad.bsenergy.co
      - LETSENCRYPT_EMAIL=lps@bsenergy.co
    depends_on:
      - nginx-proxy
      - letsencrypt
    networks:
      - webnet

volumes:
  certs:
  html:
  vhostd:
  confd:
  acme:

networks:
  webnet:
